services:
  netmap-app:
    build: .
    container_name: netmap-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
    environment:
      - DATABASE_URL=postgresql://netmap:netmap_password@netmap-db:5432/netmap
    depends_on:
      - netmap-db
    restart: unless-stopped

  netmap-db:
    image: postgis/postgis:16-3.4
    container_name: netmap-db
    environment:
      - POSTGRES_USER=netmap
      - POSTGRES_PASSWORD=netmap_password
      - POSTGRES_DB=netmap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  netmap-tunnel:
    image: cstrom/ssh-tunnel
    container_name: netmap-tunnel
    environment:
      - SSH_HOST=tunnel_host_or_ip_here
      - SSH_USER=admband
      - REMOTE_HOST=10.20.20.240
      - REMOTE_PORT=5432
      - LOCAL_PORT=5432
    ports:
      - "5433:5432"
    volumes:
      - ${USERPROFILE}/.ssh/id_rsa:/root/ssh/id_rsa:ro
    restart: unless-stopped

volumes:
  postgres_data:
