services:
  netmap-app:
    build: .
    container_name: netmap-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./scripts:/app/scripts
    environment:
      - DATABASE_URL=postgresql://netmap:${POSTGRES_PASSWORD}@netmap-db:5432/netmap
      - OCS_DB_HOST=${OCS_DB_HOST}
      - OCS_DB_USER=${OCS_DB_USER}
      - OCS_DB_PASS=${OCS_DB_PASS}
      - OCS_DB_NAME=${OCS_DB_NAME}
      - OCS_DB_PORT=${OCS_DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - netmap-network
      - localocs
      - npm-rede
    depends_on:
      - netmap-db
    restart: unless-stopped

  netmap-db:
    image: postgis/postgis:16-3.4
    container_name: netmap-db
    environment:
      - POSTGRES_USER=netmap
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=netmap
    ports:
      - "5432:5432"
    volumes:
      - pg_data_netmap:/var/lib/postgresql/data
    networks:
      - netmap-network
    restart: unless-stopped

  netmap-tunnel:
    build: ./tunnel
    container_name: netmap-tunnel
    profiles: [ "tunnel" ]
    ports:
      - "5433:3306"
    volumes:
      - ${SSH_KEY_PATH}:/root/ssh/id_ed25519:ro
    environment:
      - SSH_USER=${SSH_USER:-admband}
      - SSH_HOST=${SSH_HOST}
    networks:
      - netmap-network
      - localocs
    restart: unless-stopped

volumes:
  pg_data_netmap:


networks:
  netmap-network:
  localocs:
  npm-rede:
